---
- hosts: rpi
  remote_user: pi
  become: true
  roles:
    - role: mikolak.raspi-config
      raspi_config_hostname: "{{inventory_hostname}}"
      raspi_config_replace_user:
         name: rpi
         path_to_ssh_key: "~/.ssh/id_rsa.pub"
